### ISSUE TITLE
HTTPError when requesting papers

### ISSUE THREAD

**Issue by QuLiao1117** [TideDra/zotero-arxiv-daily#1]
Traceback (most recent call last):
Retrieving Zotero corpus...
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 405, in _retrieve_data
    self.request.raise_for_status()
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: ***0 Server Error: Internal Server Error for url: https://api.zotero.org/users/***/items?itemType=conferencePaper+%7C%7C+journalArticle+%7C%7C+preprint&format=json&limit=100&locale=en-US

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 113, in <module>
    corpus = get_zotero_corpus(args.zotero_id, args.zotero_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line [21](https://github.com/QuLiao1117/zotero-arxiv-daily/actions/runs/12066688459/job/33648073879#step:4:22), in get_zotero_corpus
    corpus = zot.everything(zot.items(itemType='conferencePaper || journalArticle || preprint'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 154, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 407, in _retrieve_data
    error_handler(self, self.request, exc)
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 1644, in error_handler
    raise ze.HTTPError(err_msg(req)) from exc
pyzotero.zotero_errors.HTTPError: 
Code: ***0
URL: https://api.zotero.org/users/***/items?itemType=conferencePaper+%7C%7C+journalArticle+%7C%7C+preprint&format=json&limit=100&locale=en-US
Method: GET
Response: An error occurred
Error: Process completed with exit code 1.

How can I solve this ? Thanks

**Comment by DripNowhy** [comment]
I have the same issue.

**Comment by TideDra** [comment]
Can you re-run the workflow? It may be the network problem or the Zotero server was overloaded.

**Comment by DripNowhy** [comment]
Weird. Still the same problem. I will re-run it later. Thanks!

**Comment by TideDra** [comment]
> Weird. Still the same problem. I will re-run it later. Thanks!
You can try to run the source code of this part locally, and check whether your ID and Key are set properly
```python
from pyzotero import zotero
zot = zotero.Zotero('ZOTERO_ID','user','ZOTERO_KEY')
corpus = zot.everything(zot.items(itemType='conferencePaper || journalArticle || preprint'))
```

**Comment by DripNowhy** [comment]
> You can try to run the source code of this part locally, and check whether your ID and Key are set properly

Thank you for your reply! I tried running this code locally, and it seems the issue lies with the Zotero server.
```
Traceback (most recent call last):
  File "/Users/yiding/Desktop/from pyzotero import zotero.py", line 3, in <module>
    corpus = zot.everything(zot.items(itemType='conferencePaper || journalArticle || preprint'))
  File "/Users//Library/Python/3.9/lib/python/site-packages/pyzotero/zotero.py", line 154, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/Users//Library/Python/3.9/lib/python/site-packages/pyzotero/zotero.py", line 407, in _retrieve_data
    error_handler(self, self.request, exc)
  File "/Users//Library/Python/3.9/lib/python/site-packages/pyzotero/zotero.py", line 1644, in error_handler
    raise ze.HTTPError(err_msg(req)) from exc
pyzotero.zotero_errors.HTTPError: 
Code: 500
URL: https://api.zotero.org/users//items?itemType=conferencePaper+%7C%7C+journalArticle+%7C%7C+preprint&format=json&limit=100&locale=en-US
Method: GET
Response: An error occurred
```

**Comment by TideDra** [comment]
Weird. I can run the API successfully at this time. Are you accessing a group libarary instead of a personal libarary? Did you check your ID and Key?

**Comment by DripNowhy** [comment]
I found I wrongly set my ID as username. It works for me now. Thank you!
