### ISSUE TITLE
ValueError: Requested tokens (9902) exceed context window of 4096

### ISSUE THREAD

**Issue by yesluck** [TideDra/zotero-arxiv-daily#2]
Hi, I meet with the following error:

```
Traceback (most recent call last):
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 1[33](https://github.com/yesluck/zotero-arxiv-daily/actions/runs/12072035190/job/33665103156#step:4:34), in <module>
    p.tldr = get_paper_tldr(p, llm)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/tldr.py", line 58, in get_paper_tldr
    response = model.create_chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/llama_cpp/llama.py", line 1998, in create_chat_completion
    return handler(
           ^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/llama_cpp/llama_chat_format.py", line 6[37](https://github.com/yesluck/zotero-arxiv-daily/actions/runs/12072035190/job/33665103156#step:4:38), in chat_completion_handler
    completion_or_chunks = llama.create_completion(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/llama_cpp/llama.py", line 1832, in create_completion
    completion: Completion = next(completion_or_chunks)  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/llama_cpp/llama.py", line 1268, in _create_completion
    raise ValueError(
ValueError: Requested tokens (9902) exceed context window of 4096
```

How can I solve this? Thanks a lot!

**Comment by TideDra** [comment]
It seems that it gets a very long paper whose length exceeds LLM context. You can truncate the prompt, at line 63 of `tldr.py`, like `"content": prompt[:6000]`. This is just a temporary fix for you to test the workflow quickly, I will fix this bug later. Please notice the updates. Thanks for your report!
