### ISSUE TITLE
Question about failing to process certain characters 

### ISSUE THREAD

**Issue by 421zuoduan** [TideDra/zotero-arxiv-daily#38]
Hi, there. I've encountered an issue after updating to the latest code version. It seems like the system appears to be unable to process certain characters. Could you advise on how to resolve this compatibility problem?

```
Run uv run main.py
Using CPython 3.***.***0
Creating virtual environment at: .venv
Installed 66 packages in [24](https://github.com/421zuoduan/zotero-arxiv-daily/actions/runs/12552538915/job/34998670184#step:4:25)9ms
2024-***2-*** 22:***8:09.880 | **mINFO     | __main__:<module>:***5*** - **mRetrieving Zotero corpus...
2024-***2-*** 22:***8:***.065 | **mINFO     | __main__:<module>:***53 - **mRetrieved 507 papers from Zotero.
2024-***2-*** 22:***8:***.065 | **mINFO     | __main__:<module>:***55 - **mIgnoring papers in:
 others/
low level/
**/survey
My Work/Uncertainty/Survey...
2024-***2-*** 22:***8:***.090 | **mINFO     | __main__:<module>:***57 - **mRemaining 507 papers after filtering.
2024-***2-*** 22:***8:***.090 | **mINFO     | __main__:<module>:***58 - **mRetrieving Arxiv papers...
Traceback (most recent call last):
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line ***59, in <module>
    papers = get_arxiv_paper(args.arxiv_query, args.debug)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 5***, in get_arxiv_paper
    feed = feedparser.parse(f"https://rss.arxiv.org/atom/{query}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.***/site-packages/feedparser/api.py", line 2***6, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.***/site-packages/feedparser/api.py", line ***5, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.***/site-packages/feedparser/http.py", line ***7***, in get
    f = opener.open(request)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/urllib/request.py", line 5***9, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/urllib/request.py", line ***39***, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/urllib/request.py", line ***[34](https://github.com/421zuoduan/zotero-arxiv-daily/actions/runs/12552538915/job/34998670184#step:4:35)8, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/http/client.py", line ***3, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/http/client.py", line ***3***4, in _send_request
    self.putrequest(method, url, **skips)
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/http/client.py", line ***48, in putrequest
    self._validate_path(url)
  File "/home/runner/.local/share/uv/python/cpython-3.***.***0-linux-x86_64-gnu/lib/python3.***/http/client.py", line ***248, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/atom/***' (found at least ' ')
Error: Process completed with exit code ***.
```

**Comment by TideDra** [comment]
The latest version is not backward-compatible. The usage of `ARXIV_QUERY` is changed. You can refer to the new README and modify this environment variable.
