### ISSUE TITLE
QQ邮箱SMTP connection closed

### ISSUE THREAD

**Issue by liangbingzhao** [TideDra/zotero-arxiv-daily#9]
我的zotero备份是用的QQ邮箱smtp+坚果云那一套进行的跨设备备份的，所以QQ邮箱的smtp应该是能用的。但是会出现这个问题：
```
Traceback (most recent call last):
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 162, in <module>
    send_email(args.sender, args.receiver, args.password, args.smtp_server, args.smtp_port, html)
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 111, in send_email
    server.login(sender, password)
  File "/home/runner/.local/share/uv/python/cpython-3.11.10-linux-x86_64-gnu/lib/python3.11/smtplib.py", line 7[39](https://github.com/liangbingzhao/zotero-arxiv-daily/actions/runs/12083082487/job/33696732449#step:4:40), in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.11.10-linux-x86_64-gnu/lib/python3.11/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.11.10-linux-x86_64-gnu/lib/python3.11/smtplib.py", line 432, in docmd
    return self.getreply()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/uv/python/cpython-3.11.10-linux-x86_64-gnu/lib/python3.11/smtplib.py", line [40](https://github.com/liangbingzhao/zotero-arxiv-daily/actions/runs/12083082487/job/33696732449#step:4:41)5, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```
这该怎么解决啊

**Comment by longyun200111** [comment]
我遇到了一样的问题，原因是qq邮箱只接受SSL连接，单独对qq邮箱使用SMTP_SSL就可以了。我在 #10 里修复了这个问题

**Comment by liangbingzhao** [comment]
@longyun200111 xd我cp了你修改的；还是报一样的错啊；难道是我QQ邮箱smtp的问题？是password是填的QQ邮箱授权码吧。
我port也改了

**Comment by liangbingzhao** [comment]
我之前设置的是secret，现在又设置了variable，不太清楚这俩啥区别，但是设置了variable后，报错变成了：
```
Traceback (most recent call last):
Namespace(zotero_id='***', zotero_key='***', max_paper_num=***, arxiv_query='***', smtp_server='***', smtp_port=***, sender='***\n', receiver='***', password='***', debug=True)
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 405, in _retrieve_data
    self.request.raise_for_status()
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.zotero.org/users/***/items?itemType=conferencePaper+%7C%7C+journalArticle+%7C%7C+preprint&format=json&limit=100&locale=en-US
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line 144, in <module>
    corpus = get_zotero_corpus(args.zotero_id, args.zotero_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/main.py", line [22](https://github.com/liangbingzhao/zotero-arxiv-daily/actions/runs/12089653189/job/33715422641#step:4:23), in get_zotero_corpus
    corpus = zot.everything(zot.items(itemType='conferencePaper || journalArticle || preprint'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 154, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 407, in _retrieve_data
    error_handler(self, self.request, exc)
  File "/home/runner/work/zotero-arxiv-daily/zotero-arxiv-daily/.venv/lib/python3.11/site-packages/pyzotero/zotero.py", line 1639, in error_handler
    raise error_codes.get(req.status_code)(err_msg(req)) from exc
pyzotero.zotero_errors.UserNotAuthorised: 
Code: 403
URL: https://api.zotero.org/users/***/items?itemType=conferencePaper+%7C%7C+journalArticle+%7C%7C+preprint&format=json&limit=100&locale=en-US
Method: GET
Response: Invalid key
```

**Comment by longyun200111** [comment]
应该就是设置 secret，你后面出现的这个报错应该是 zotero 的 key 设置有问题。我修改之后 qq 邮箱没问题可以正常发出邮件了，password 是用授权码，你确定用的是修改后的代码吗？

**Comment by liangbingzhao** [comment]
确实，zotero key好像被我删掉了；我现在改好后，代码也是按照你那样来的，但是还是跟这个issue最开始一样的报错

**Comment by TideDra** [comment]
qq邮箱服务器smtp.qq.com，端口号25，再检查一遍呢。或者本地跑一下main.py里send_email的代码

**Comment by liangbingzhao** [comment]
qq邮箱smtp服务是465或者587，不是25. 我现在本地用587，然后不改代码是能发送邮件的。465好像是要按照上面那位的修改代码。但是我465跑不通的。但是改成587后，github上还是不行。还是一样的错误

**Comment by TideDra** [comment]
很奇怪，我用qq邮箱25就能跑，可能是qq本身原因。实在不行可以尝试其他邮箱

在 2024年11月30日，19:18，zzmartin ***@***.***> 写道：

﻿

qq邮箱smtp服务是465或者587，不是25. 我现在本地用587，然后不改代码是能发送邮件的。465好像是要按照上面那位的修改代码。但是我465跑不通的。但是改成587后，github上还是不行。还是一样的错误

**Comment by longyun200111** [comment]
我这边是本地和github都需要修改后用465，如果用587无论改不改都会报错。25我没试过，我是看smtp服务的说明上说要SSL连接465或587端口，所以才用的这两个。我猜或许25是以前用来非SSL连接的端口，现在仍然为了兼容性而保留，但是官方为了推广SSL而不再对外提及它了？

**Comment by longyun200111** [comment]
我发现587好像不是很稳定，我这边连续不断重复，大概重复个五六次就会有一次成功的

**Comment by TideDra** [comment]
fixed by #14
